"""empty message

Revision ID: 0fdc9decb634
Revises: 3ec200bb2a4a
Create Date: 2023-10-12 19:08:47.525524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdc9decb634'
down_revision = '3ec200bb2a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('current_inventory', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
