"""Last4Digits

Revision ID: 62a874e0b549
Revises: b0cf57c82809
Create Date: 2023-11-09 20:08:47.747024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a874e0b549'
down_revision = 'b0cf57c82809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_four_digits', sa.String(length=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('last_four_digits')

    # ### end Alembic commands ###
