"""ItemInCartCount

Revision ID: 6aeb85bd21e7
Revises: 3d0d8e72bd48
Create Date: 2023-10-22 19:57:46.624700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aeb85bd21e7'
down_revision = '3d0d8e72bd48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
