"""NoMoreItemInCartCount

Revision ID: 73e936e186dc
Revises: 6aeb85bd21e7
Create Date: 2023-10-22 20:19:31.599664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e936e186dc'
down_revision = '6aeb85bd21e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
