"""empty message

Revision ID: aefdd473700e
Revises: 0fdc9decb634
Create Date: 2023-10-15 11:11:26.539794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefdd473700e'
down_revision = '0fdc9decb634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cart_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
