"""ManyToManyCartItemWithProperties

Revision ID: c7c723e403be
Revises: 2d05758b3a00
Create Date: 2023-10-29 13:04:55.612414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c723e403be'
down_revision = '2d05758b3a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), server_default='1', nullable=False))
        batch_op.alter_column('cart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('count')

    # ### end Alembic commands ###
