"""CartRequiresAuthentication

Revision ID: d53e828c499d
Revises: eacb4f9b1d50
Create Date: 2023-10-22 18:30:42.781579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53e828c499d'
down_revision = 'eacb4f9b1d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('cart_guid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_guid', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
